### ISSUE TITLE
Congrats on first 1k github stars!

### ISSUE THREAD

**Issue by stevemao** [you-dont-need/You-Dont-Need-Momentjs#11]
<img width="147" alt="screen shot 2018-09-13 at 7 40 39 am" src="https://user-images.githubusercontent.com/6316590/45454777-5ce6bb00-b728-11e8-82c5-caefff291b54.png">

Congrats to all the contributors! Go team!
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by stmoreau** [comment]
Congrats on 2k github stars!
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by stevemao** [comment]
<img width="151" alt="screen shot 2018-09-15 at 10 28 34 am" src="https://user-images.githubusercontent.com/6316590/45580227-20ef5980-b8d2-11e8-8fb0-49261eaa7888.png">

**Comment by stevemao** [comment]
3K stars now!

<img width="148" alt="screen shot 2018-09-16 at 2 12 50 pm" src="https://user-images.githubusercontent.com/6316590/45592791-a77f6600-b9ba-11e8-873e-636da7fc6901.png">

**Comment by stevemao** [comment]
4.6k stars now. Good job team!

<img width="149" alt="screen shot 2018-09-20 at 12 55 33 pm" src="https://user-images.githubusercontent.com/6316590/45793230-837e9600-bcd4-11e8-9e67-9afe7de92793.png">

**Comment by stevemao** [comment]
5k stars now! That's CRAZY!

<img width="144" alt="screen shot 2018-09-23 at 9 10 18 am" src="https://user-images.githubusercontent.com/6316590/45922502-8f569c00-bf10-11e8-9783-95e4ee5c32a5.png">
