### ISSUE TITLE
moment js size optimization with webpack

### ISSUE THREAD

**Issue by exiadbq** [you-dont-need/You-Dont-Need-Momentjs#12]
Here is walkaround if needed to reduce moment js size, which is not needed in alternatives. ;)

See if this helps.

https://github.com/jmblog/how-to-optimize-momentjs-with-webpack

**Comment by stevemao** [comment]
Too much configuration and trick to enable this... If one uses browserify or parcel then someone needs to write another article for that. Even in the [bonus section](https://github.com/jmblog/how-to-optimize-momentjs-with-webpack#bonus) the author mentions date-fns.

**Comment by dmngu9** [comment]
i overwrite moment-timezone because i only need Sydney/ Australia zone and exclude locales. The parsed size reduce to 50kb while luxon is 63kb
