### ISSUE TITLE
You-Dont-Need-date-fns

### ISSUE THREAD

**Issue by HiZhaoxiaoyang** [you-dont-need/You-Dont-Need-Momentjs#28]
https://github.com/HiZhaoxiaoyang/You-Dont-Need-date-fns.git

**Comment by stevemao** [comment]
I like the native examples in your list (even though date-fns is doing more or less the same so you're repeating yourself). Maybe send us a PR so that we have more alternatives?

**Comment by ddvkid** [comment]
I like your work of making the native date examples, I was trying to do this when I first started this repo, however, I then realize no one will use these complex methods in a real project, you will need a lib at the end of the day, and this is exactly what `date-fns` is doing.
