### ISSUE TITLE
subDays into sub_days

### ISSUE THREAD

**Issue by seohyun0120** [you-dont-need/You-Dont-Need-Momentjs#32]
hello I tried to use date_fns but there are some problems
I tried to **import subDays from 'date-fns/subDays'** but it doesn't work.
So I found out something thorough the document. 

https://date-fns.org/v1.28.5/docs/subDays
According to this document, **date-fns/subDays** should be changed to **date-fns/sub_days**
Am I correct?

**Comment by stevemao** [comment]
In the readme:
> ⚠️ Note that the provided examples of date-fns are for v2 which is in pre-release right now. See v1 docs for the current release.

Also see https://github.com/you-dont-need/You-Dont-Need-Momentjs/pull/7 for discussion

**Comment by seohyun0120** [comment]
thank you
