### ISSUE TITLE
Timezone support

### ISSUE THREAD

**Issue by 4ver** [you-dont-need/You-Dont-Need-Momentjs#4]
You might mention that if you need to format dates for a timezone that's not that of the host then you can't use date-fns/native dates right now.

**Comment by ttma1046** [comment]
Isn't 'timezone' in the context of this repo ? "You dont need momentjs" not "You dont need momentjs and moment-timezone".

**Comment by ddvkid** [comment]
Fortunately, moment-timezone did a really great job of supporting timezone on javascript. Unfortunately, it seems the only mature one in the market right now, and it requires moment.js. We will keep eyes on the timezone libs, and will update the docs once they are decent enough.

**Comment by 4ver** [comment]
I wan't talking about moment-timezone. Moments `utcOffset` function has no equivalent in either Date/date-fns https://momentjs.com/docs/#/manipulating/utc-offset/

Is about the only exception I think (and a pretty big one if you need it) so it might be worth noting it in this repo.

**Comment by ddvkid** [comment]
mentioned in new README
