### ISSUE TITLE
dateFns.formatDistance is deprecated. Use distanceInWordsToNow instead.

### ISSUE THREAD

**Issue by ruffle1986** [you-dont-need/You-Dont-Need-Momentjs#46]
`formatDistance` is a date-fns function to replace `moment.fromNow()`

It's not in the latest version of the package and you cannot find it in the docs anymore. 
We should use `distanceInWordsToNow` instead.

https://date-fns.org/v1.29.0/docs/distanceInWordsToNow

Shall I update the readme?

**Comment by ODudek** [comment]
We're using `2.0.0-alpha.16` version and you're checking `1.29.0` version. Method `distanceInWordsToNow` was deprecated in `v2` and was replaced by `formatDistance`

**Comment by ruffle1986** [comment]
Indeed. Thank you!

Great job btw! 👍
