### ISSUE TITLE
How does date-fns compare to dayjs?

### ISSUE THREAD

**Issue by antony** [you-dont-need/You-Dont-Need-Momentjs#6]
Dayjs claims to replicate the momentjs API in 2kb. I've been using it as a replacement recently.

It would be good to add this to the comparison I think.

https://github.com/iamkun/dayjs

**Comment by corbinu** [comment]
I just use luxon ... also I don't see anything about handling timezones in the repo?

**Comment by stevemao** [comment]
Dayjs is added. What about luxon?

**Comment by millette** [comment]
Comparing luxon and moment: https://moment.github.io/luxon/docs/manual/moment.html
