### ISSUE TITLE
Repo description update

### ISSUE THREAD

**Issue by xxyuk** [you-dont-need/You-Dont-Need-Momentjs#69]
> List of date-fns or native functions which you can use to replace moment.js + ESLint Plugin

Thanks for this amazing repo. Above is the description of our repo. Since we have dayjs and luxon right now, should we update the description accordingly?

**Comment by stevemao** [comment]
What about 
```
List of functions which you can use to replace moment.js + ESLint Plugin 
```
?

**Comment by xxyuk** [comment]
Looks good 😬

**Comment by stevemao** [comment]
Done. thanks for the suggestion :)
