### ISSUE TITLE
Time Zone support does exist in date-fns

### ISSUE THREAD

**Issue by zArubaru** [you-dont-need/You-Dont-Need-Momentjs#86]
It would seem that date-fns does at least have some Time Zone support.
https://date-fns.org/v2.9.0/docs/Time-Zones

This information should be updated here:
https://github.com/you-dont-need/You-Dont-Need-Momentjs#brief-comparison

**Comment by stevemao** [comment]
@zArubaru 
It didn't when we created this project.
PR welcome :)
