### ISSUE TITLE
Linked Moment Tests don't support bugs argument?

### ISSUE THREAD

**Issue by micnguyen** [you-dont-need/You-Dont-Need-Momentjs#87]
In the README, there's a line that says `It is mutable due to OOP APIs and non-pure functions, which cause bugs:` with a link to https://github.com/moment/moment/blob/develop/src/test/moment/add_subtract.js#L244-L286

I'm looking at these tests and I can't seem to pin point why these tests might support the line `which cause bugs`. Sure, the API is a bit verbose and it is OOP vs pure, but I don't think it's buggy.

**Comment by stevemao** [comment]
I did a git blame and saw @ddvkid wrote that line.

**Comment by ddvkid** [comment]
Good catch, I will make an update on that, thanks!
